export const PAYMENT_CONFIG = {
  CREDIT_PRICE_INR: 50,
  CREDIT_PRICE_USD: 5,
  SESSION_DURATION_SECONDS: 600, // 10 minutes
  PLATFORM_SHARE_PERCENT: 50,
  PARTNER_SHARE_PERCENT: 50,
  SATISFACTION_THRESHOLD: 90,
  PENALTY_MULTIPLIER: 0.5,
  MIN_WITHDRAWAL_INR: 500,
  MIN_WITHDRAWAL_USD: 10,
  ESCROW_HOLD_HOURS: 24,
  TRIAL_DURATION_HOURS: 24,
  MASKED_DESCRIPTION: "Global Social Credits",
} as const;
